# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'ProjetoIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
    pod 'SwiftyDropbox'
  # Pods for ProjetoIOS
  # pod 'SwiftyDropbox', :git => 'git@github.com:dropbox/SwiftyDropbox.git', :tag => '0.2'
end
